
import = ["~/Developer/poimandres-storm.toml"]

# needed for tmux
# [env] 
# TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.8
blur = true

[font]
normal = { family = "SFMono Nerd Font", style = "Light" }
bold = { style = "Regular" }
italic = { style = "Light Italic" }
bold_italic = { style = "Regular Italic" }
size = 19
